library(SCAP)
pbmc.data = readRDS("../R-Programming-2/data/pbmc.rds")
pbmc = CreateMySCO(pbmc.data)
pbmc = CalcMitoPct(pbmc, "^MT-")
pbmc = FilterData(pbmc, 200, 2500, 0.05, 3)
MakeQCPlots(pbmc)
pbmc = NormaliseData(pbmc, 10000)
pbmc = FindHVGs(pbmc, 2000)
PlotHVGs(pbmc)
pbmc = ScaleData(pbmc)
pbmc = CalcPC(pbmc)
pbmc = ClusterData(pbmc, n_pc = 10, n_neighbours = 30)
MakeUMAP(pbmc)
